version: "3"
services:
  worker-pi-1:
    image: nebulastream/nes-elegant-image:elegant-v0.6.16
    entrypoint: ["bash", "-c", "sleep 3 && nesWorker --configPath=/ubidemo/distributed_configuration/worker-pi-1.yml"]
    volumes:
      - ../:/ubidemo
    network_mode: host
