version: "3"
services:
    kafka:
      image: landoop/fast-data-dev:latest
      ports:
        - 2181:2181
        - 3030:3030
        - 8081:8081
        - 8082:8082
        - 8083:8083
        - 9092:9092
        - 9581:9581
        - 9582:9582
        - 9583:9583
        - 9584:9584
      environment:
        ADV_HOST: 127.0.0.1
      network_mode: "host"
  
    video-collector:
      build:
        context: ./video-stream-collector
      network_mode: "host"
      depends_on: 
       - kafka
 
    video-processor:
      build:
        context: ./video-stream-processor
      depends_on: 
       - video-collector
      network_mode: "host"



